config/routes.rb
Elastic::Application.routes.draw do

  resources :downloaders do
    member do
      get :download_file
    end
  end

  resources :segments

  devise_for :users, controllers: { registrations: 'contour/registrations', sessions: 'contour/sessions', passwords: 'contour/passwords', confirmations: 'contour/confirmations', unlocks: 'contour/unlocks' }, path_names: { sign_up: 'register', sign_in: 'login' }

  resources :users do
    member do
      post :update_settings
    end
  end

  get "/about" => "application#about", as: :about
  get "/settings" => "users#settings", as: :settings

  root to: "downloaders#index"

  # See how all your routes lay out with "rake routes"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, and :lockable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :trackable, :validatable

  # Callbacks
  after_create :notify_system_admins

  STATUS = ["active", "denied", "inactive", "pending"].collect{|i| [i,i]}
  serialize :email_notifications, Hash

  # Concerns
  include Contourable

  # Named Scopes
  scope :current, -> { where deleted: false }
  scope :status, lambda { |arg|  where( status: arg ) }
  scope :system_admins, -> { where system_admin: true }
  scope :search, lambda { |arg| where( 'LOWER(first_name) LIKE ? or LOWER(last_name) LIKE ? or LOWER(email) LIKE ?', arg.to_s.downcase.gsub(/^| |$/, '%'), arg.to_s.downcase.gsub(/^| |$/, '%'), arg.to_s.downcase.gsub(/^| |$/, '%') ) }

  # Model Validation
  validates_presence_of     :first_name
  validates_presence_of     :last_name

  # Model Relationships
  has_many :authentications
  has_many :downloaders, -> { where deleted: false }
  has_many :segments # Segments don't have a deleted flag

  # User Methods

  def all_downloaders
    if self.system_admin?
      Downloader.current
    else
      self.downloaders
    end
  end

  def all_segments
    if self.system_admin?
      Segment.current
    else
      self.segments
    end
  end

  # Overriding Devise built-in active_for_authentication? method
  def active_for_authentication?
    super and self.status == 'active' and not self.deleted?
  end

  def destroy
    update_column :deleted, true
    update_column :status, 'inactive'
    update_column :updated_at, Time.now
  end

  def email_on?(value)
    [nil, true].include?(self.email_notifications[value.to_s])
  end

  def name
    "#{first_name} #{last_name}"
  end

  def reverse_name
    "#{last_name}, #{first_name}"
  end

  def nickname
    "#{first_name} #{last_name.first}"
  end

  # Override of Contourable
  def apply_omniauth(omniauth)
    unless omniauth['info'].blank?
      self.first_name = omniauth['info']['first_name'] if first_name.blank?
      self.last_name = omniauth['info']['last_name'] if last_name.blank?
    end
    super
  end

  private

  def notify_system_admins
    User.current.system_admins.each do |system_admin|
      UserMailer.notify_system_admin(system_admin, self).deliver if Rails.env.production?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [ :new, :create ]
  before_action :check_system_admin, except: [ :new, :create, :index, :show, :settings, :update_settings ]
  before_action :set_user, only: [ :show, :edit, :update, :destroy ]
  before_action :redirect_without_user, only: [ :show, :edit, :update, :destroy ]

  def settings
  end

  def update_settings
    notifications = {}
    email_settings = ['send_email']
    email_settings.each do |email_setting|
      notifications[email_setting] = (not params[:email].blank? and params[:email][email_setting] == '1')
    end
    current_user.update_attributes email_notifications: notifications
    redirect_to settings_path, notice: 'Email settings saved.'
  end

  def index
    current_user.update_column :users_per_page, params[:users_per_page].to_i if params[:users_per_page].to_i >= 10 and params[:users_per_page].to_i <= 200
    @order = scrub_order(User, params[:order], 'users.current_sign_in_at DESC')
    @users = User.current.search(params[:search]).order(@order).page(params[:page]).per(current_user.users_per_page)
  end

  def show
  end

  def edit
  end

  def update
    original_status = @user.status
    if @user.update(user_params)
      UserMailer.status_activated(@user).deliver if Rails.env.production? and original_status != @user.status and @user.status == 'active'
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted.'
  end

  private

    def set_user
      @user = User.current.find_by_id(params[:id])
    end

    def redirect_without_user
      empty_response_or_root_path(users_path) unless @user
    end

    def user_params
      params[:user] ||= {}

      params.require(:user).permit(
        :first_name, :last_name, :email, :password, :password_confirmation, :system_admin, :status
      )
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="page-header">
  <h1><%= @title %></h1>
</div>

<%= form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :first_name, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :last_name, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :status, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.select :status, User::STATUS %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :email, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :email %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :system_admin, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.check_box :system_admin %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= cancel %>
  </div>
<% end %>

app/views/users/_users.html.erb
<%= render partial: 'contour/layouts/per_page', locals: { type: 'users', object_count: @users.total_count } %>

<table class="table table-striped table-bordered" style="width:100%">
  <thead>
    <tr>
      <th style="white-space:nowrap"><%== sort_field_helper(@order, 'users.last_name', 'Name', 'users_search') %></th>
      <th style="white-space:nowrap"><%== sort_field_helper(@order, 'users.email', 'Email', 'users_search') %></th>
      <th style="white-space:nowrap"><%== sort_field_helper(@order, 'users.current_sign_in_at', 'Recent Activity', 'users_search') %></th>
      <% if current_user.system_admin? %>
        <th style="white-space:nowrap"><%== sort_field_helper(@order, 'users.status', 'Status', 'users_search') %></th>
        <th style="white-space:nowrap"><%== sort_field_helper(@order, 'users.system_admin', 'System Admin', 'users_search') %></th>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>

  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= recent_activity(user.current_sign_in_at) %></td>
      <% if current_user.system_admin? %>
        <td><%= user.status %></td>
        <td style="text-align:center"><%= check_box_tag 'user', 'system_admin', user.system_admin?, disabled: true %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-mini' %>
          <% unless current_user == user %>
            <%= link_to 'Delete', user, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: "Are you sure you want to delete User #{user.name}?" } %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

<center><%= paginate @users, theme: "contour" %></center>

app/views/users/edit.html.erb
<% @title = "Edit User: #{@user.name}" %>

<%= render 'form' %>

app/views/users/index.html.erb
<% @title = 'Users' %>
<div class="page-header">
  <h1>
    <%= @title %>
    <%= link_to "Create User", new_user_path, class: 'btn btn-primary btn-mini' if current_user.system_admin? and false %>
  </h1>
</div>

<%= form_tag users_path, method: :get, remote: true, id: "users_search", class: 'form-search', data: { object: 'form-load' } do %>
  <%= hidden_field_tag :order %>
  <%= text_field_tag 'search', params[:search], class: 'search-query' %>
  <%= submit_tag 'Search', class: 'btn btn-primary' %>
<% end %>

<div id="users"><center><%= image_tag "contour/ajax-loader.gif" %></center></div>

app/views/users/index.js.erb
$("#users").html("<%= escape_javascript(render("users")) %>");

app/views/users/settings.html.erb
<% @title = "My Settings" %>
<div class="page-header">
  <h1><%= @title %></h1>
</div>

<%= hidden_field_tag 'isdirty', '1' %>

<%= form_tag update_settings_user_path(current_user), :method => :post, id: 'email_settings', class: 'form-horizontal' do %>
  <div class="control-group">
    <div class="controls">
      <%= check_box_tag 'email[send_email]', '1', current_user.email_on?(:send_email) %> <%= 'Receive Emails' %>
    </div>
  </div>

  <div class="form-actions">
    <% form_name = "email_settings" %>
    <%= link_to "Save Settings", '#', class: 'btn btn-primary', data: { object: 'settings-save', target: "##{form_name}" } %>
  </div>
<% end %>

app/views/users/show.html.erb
<% @title = "User: #{@user.name}" %>
<div class="page-header">
  <h1>
    <%= @title %>
    <% if current_user.system_admin? %>
      <%= link_to "Edit User", edit_user_path(@user), class: 'btn btn-mini' %>
      <%= link_to 'Delete User', @user, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: "Are you sure you want to delete User #{@user.name}?" } unless current_user == @user %>
      <%= link_to "View Users", users_path, class: 'btn btn-mini' %>
    <% end %>
  </h1>
</div>

<dl class="dl-horizontal">
  <dt>Email</dt>
  <dd><%= @user.email %></dd>

  <% if current_user.system_admin? %>
    <dt>Status</dt>
    <dd><%= @user.status %></dd>

    <dt>System Admin</dt>
    <dd><%= simple_check @user.system_admin? %></dd>
  <% end %>
</dl>