config/routes.rb
Elastic::Application.routes.draw do

  resources :downloaders do
    member do
      get :download_file
    end
  end

  resources :segments

  devise_for :users, controllers: { registrations: 'contour/registrations', sessions: 'contour/sessions', passwords: 'contour/passwords', confirmations: 'contour/confirmations', unlocks: 'contour/unlocks' }, path_names: { sign_up: 'register', sign_in: 'login' }

  resources :users do
    member do
      post :update_settings
    end
  end

  get "/about" => "application#about", as: :about
  get "/settings" => "users#settings", as: :settings

  root to: "downloaders#index"

  # See how all your routes lay out with "rake routes"
end

app/models/downloader.rb
class Downloader < ActiveRecord::Base
  # attr_accessible :name, :comments, :download_token, :simple_executable_file, :folder, :external_user_id, :files_digest, :target_file_name

  # Concerns
  include Searchable

  # Named Scopes
  scope :current, -> { where deleted: false }

  # Model Validation
  validates_presence_of :name

  # Model Relationships
  belongs_to :user
  has_many :downloader_segments
  has_many :segments, through: :downloader_segments

  attr_reader :files

  mount_uploader :simple_executable_file, FileUploader

  def destroy
    update_column :deleted, true
  end

  def simple_executable_file_url
    (self.simple_executable_file and self.simple_executable_file.url) ? SITE_URL + self.simple_executable_file.url : ''
  end

  def file_count
    # self.files.to_s.split(/[\r\n]/).select{|i| not i.blank?}.size
    self.downloader_segments.size
  end

  def self.filter_files(params_files = '', params_folder = '')
    available_files = []
    updated_file_locations = []
    params_files.to_s.split(/[\r\n]/).each do |file|
      file_location = File.join(Rails.root, 'tmp', 'symbolic', params_folder, File.basename(file))
      if File.exists?(file_location) and not file.blank?
        updated_file_locations << file_location
        available_files << File.basename(file)
        # Rails.logger.debug "#{file_location} ADDED!"
      else
        # Rails.logger.debug "#{file_location} does NOT exist"
      end
    end

    return { base: available_files.compact.uniq.sort.join("\n"), path: updated_file_locations.compact.uniq.sort }
  end

  # def generate_checksums!
  #   updated_file_locations = Downloader.filter_files(self.files, self.folder)[:path]
  #   updated_file_locations.each do |file_location|
  #     logger.debug "Searching for CHECKSUM!: #{file_location}"
  #     # TODO find by file path
  #     segment = Segment.find_or_create_by_file_path(file_location)
  #   end
  # end

  # `-- <rails_root>
  #     |-- ...
  #     `-- tmp
  #         |-- cache
  #         |-- files
  #         |   |-- executable_file_path (.exe)   ex:   my_files.exe      <= The compiled script (contains both .rb)
  #         |   `-- script_file_path (.rb)        ex:   my_files.rb       <= The ruby script that downloads the target files
  #         |-- pids
  #         |-- sessions
  #         |-- sockets
  #         `-- symbolic


  def generate_simple_executable!
    # self.generate_checksums!

    if ENV['OS'] == "Windows_NT" or true
      # begin
        script_file_path = File.join('tmp', 'files', "simple_download_#{self.id}.rb")
        file_template = File.join('lib', 'templates', 'simple_download.rb.erb')

        file_in = File.new(file_template, "r")
        file_out = File.new(script_file_path, "w")
        template = ERB.new(file_in.sysread(File.size(file_in)))
        file_out.syswrite(template.result(binding))
        file_in.close()
        file_out.close()

        executable_file_path = File.join(File.dirname(script_file_path), File.basename(script_file_path, ".rb") + ".exe")

        FileUtils.cd(File.join('tmp', 'files'))

        ocra_cmd = "ocra #{File.basename(script_file_path)}"
        logger.debug ocra_cmd

        t = Time.now
        logger.debug "Waiting on ocra..."

        status, stdout, stderr = systemu ocra_cmd

        logger.debug "Status: #{status}\nStdout: #{stdout}\nStderr: #{stderr}"

        FileUtils.cd(Rails.root)

        if File.exists?(executable_file_path)
          exe_file = File.new(executable_file_path)
          self.simple_executable_file = exe_file
          self.save
          exe_file.close
        end

        logger.debug "Deleting #{executable_file_path}"
        File.delete(executable_file_path) if File.exists?(executable_file_path)
        logger.debug "Deleting #{script_file_path}"
        File.delete(script_file_path) if File.exists?(script_file_path)
      # rescue => e
      #   logger.debug "Exception: #{e.inspect}"
      # end
    end
  end

  def generate_segments!(new_files, new_folder)
    updated_file_locations = Downloader.filter_files(new_files, new_folder)[:path]
    updated_file_locations.each do |file_location|
      segment = Segment.where(file_path: file_location).first_or_create
      self.segments << segment unless self.segments.pluck('segments.id').include?(segment.id)
    end
  end
end

app/controllers/downloaders_controller.rb
class DownloadersController < ApplicationController
  before_action :authenticate_user!, except: [ :download_file ]
  before_action :check_system_admin, except: [ :download_file, :index ]
  before_action :set_downloader, only: [ :show, :edit, :update, :destroy ]
  before_action :redirect_without_downloader, only: [ :show, :edit, :update, :destroy ]

  def download_file
    @downloader = Downloader.find_by_id_and_download_token(params[:id], params[:download_token])

    file_path = File.join(Rails.root, 'tmp', 'symbolic', @downloader.folder, params[:file_path]) if @downloader
    @segment = @downloader.segments.find_by_file_path(file_path) if @downloader
    @downloader_segment = @segment.downloader_segments.find_by_downloader_id(@downloader.id) if @segment

    if @downloader and @segment and @downloader_segment
      if File.exists?(@segment.file_path)
        if params[:checksum] == '1'
          @downloader_segment.update_attributes checksum_count: @downloader_segment.checksum_count + 1
          render text: (@segment.checksum.blank? ? @segment.generate_checksum! : @segment.checksum)
        else
          @downloader_segment.update_attributes download_count: @downloader_segment.download_count + 1
          send_file @segment.file_path, disposition: 'attachment'
        end
      else
        error = "The file is no longer available"
        Rails.logger.debug error
        render text: error, status: 404, layout: false
      end
    else
      error = "No longer authorized to download this file"
      Rails.logger.debug error
      render text: error, status: 404
    end
  end

  # GET /downloaders
  # GET /downloaders.json
  def index
    @order = scrub_order(Downloader, params[:order], 'downloaders.name')
    @downloaders = current_user.all_downloaders.search(params[:search]).order(@order).page(params[:page]).per(20)
  end

  # GET /downloaders/1
  # GET /downloaders/1.json
  def show
    @downloader.generate_simple_executable! if @downloader.simple_executable_file_url.blank?
  end

  # GET /downloaders/new
  def new
    @downloader = current_user.downloaders.new
  end

  # GET /downloaders/1/edit
  def edit
  end

  # POST /downloaders
  # POST /downloaders.json
  def create
    new_files = Downloader.filter_files(params[:downloader][:files], params[:downloader][:folder])[:base]
    params[:downloader][:files_digest] = Digest::SHA1.hexdigest(new_files)

    params[:downloader][:name] = new_files.split(/[\r\n]/).first if params[:downloader][:name].blank?
    params[:target_file_name] = params[:downloader][:name] if params[:target_file_name].blank?

    params[:downloader] = downloader_params


    params[:downloader][:download_token] = Digest::SHA1.hexdigest(Time.now.usec.to_s)

    @downloader = current_user.downloaders.find_by_files_digest_and_folder_and_external_user_id(params[:downloader][:files_digest], params[:downloader][:folder], params[:downloader][:external_user_id])

    if @downloader
      @downloader.generate_simple_executable! if @downloader.simple_executable_file_url.blank?

      respond_to do |format|
        format.html { redirect_to @downloader, notice: 'Equivalent downloader retrieved.' }
        format.json { render action: 'show', status: :created, location: @downloader }
      end
    else

      @downloader = current_user.downloaders.new(downloader_params)

      respond_to do |format|
        if @downloader.save
          @downloader.generate_segments!(new_files, params[:downloader][:folder])
          @downloader.generate_simple_executable!
          format.html { redirect_to @downloader, notice: 'Downloader was successfully created.' }
          format.json { render action: 'show', status: :created, location: @downloader }
        else
          format.html { render action: 'new' }
          format.json { render json: @downloader.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /downloaders/1
  # PUT /downloaders/1.json
  def update
    new_files = Downloader.filter_files(params[:downloader][:files], params[:downloader][:folder])[:base]
    params[:downloader][:files_digest] = Digest::SHA1.hexdigest(new_files)
    params[:downloader] = downloader_params

    same_files = (params[:downloader][:files_digest] == @downloader.files_digest and params[:downloader][:folder] == @downloader.folder)

    respond_to do |format|
      if @downloader.update(params[:downloader])
        @downloader.generate_simple_executable! unless same_files
        format.html { redirect_to @downloader, notice: 'Downloader was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @downloader.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /downloaders/1
  # DELETE /downloaders/1.json
  def destroy
    @downloader.destroy

    respond_to do |format|
      format.html { redirect_to downloaders_path, notice: 'Downloader was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_downloader
      @downloader = Downloader.current.find_by_id(params[:id])
    end

    def redirect_without_downloader
      empty_response_or_root_path unless @downloader
    end

    def downloader_params
      params.require(:downloader).permit(
        :name, :comments, :download_token, :simple_executable_file, :folder, :external_user_id, :files_digest, :target_file_name
      )
    end

end

app/helpers/downloaders_helper.rb
module DownloadersHelper
end

app/views/downloaders/_downloaders.html.erb
<%= render partial: 'contour/layouts/per_page', locals: { type: 'downloaders', per_page: [20, @downloaders.count].min, object_count: @downloaders.total_count } %>

<table class="table table-striped table-bordered" style="width:100%">
  <thead>
    <tr>
      <th style="white-space:nowrap">User</th>
      <th style="white-space:nowrap">Name</th>
      <th style="white-space:nowrap">Files</th>
      <th style="white-space:nowrap">Simple Executable file</th>
      <th style="white-space:nowrap">Download Count</th>
      <th style="white-space:nowrap">Checksum Count</th>
      <th style="white-space:nowrap">External User ID</th>
      <th>Actions</th>
    </tr>
  </thead>

  <% @downloaders.each do |downloader| %>
    <tr>
      <td><%= downloader.user_id %></td>
      <td><%= link_to downloader.name, downloader %></td>
      <td><%= downloader.file_count %></td>
      <td><%= link_to File.basename(downloader.simple_executable_file.path), SITE_URL + downloader.simple_executable_file.url, :class => 'noicon' if downloader.simple_executable_file and downloader.simple_executable_file.url %></td>
      <td><%= downloader.downloader_segments.pluck(:download_count).sum %></td>
      <td><%= downloader.downloader_segments.pluck(:checksum_count).sum %></td>
      <td><%= downloader.external_user_id %></td>
      <td>
        <%= link_to 'Edit', edit_downloader_path(downloader), class: 'btn btn-mini' %>
        <%= link_to 'Destroy', downloader, :method => :delete, class: 'btn btn-mini btn-danger', data: { confirm: "Are you sure you want to delete Downloader #{downloader.name}?" } %>
      </td>
    </tr>
  <% end %>
</table>

<center><%= paginate @downloaders, theme: "contour" %></center>

app/views/downloaders/_form.html.erb
<div class="page-header">
  <h1><%= @title %></h1>
</div>

<%= form_for(@downloader, html: { class: 'form-horizontal' }) do |f| %>
  <% if @downloader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@downloader.errors.count, "error") %> prohibited this downloader from being saved:</h2>

      <ul>
      <% @downloader.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :files, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :files, rows: 7, style: 'width:95%' %>
    </div>
  </div>

  <div class="control-group">
    <%= label 'target', 'file_name', 'Target file name', class: 'control-label' %>
    <div class="controls">
      <%= text_field_tag :target_file_name, @downloader.simple_executable_file.blank? ? '' : File.basename(@downloader.simple_executable_file.path.split('_')[0..-4].join('_')) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :comments, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :comments, rows: 7, style: 'width:95%' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= cancel %>
  </div>
<% end %>

app/views/downloaders/edit.html.erb
<% @title = "Edit Downloader: #{@downloader.name}" %>

<%= render 'form' %>

app/views/downloaders/index.html.erb
<% @title = 'Downloaders' %>
<div class="page-header">
  <h1>
    <%= @title %>
    <%= link_to "Create Downloader", new_downloader_path, class: 'btn btn-primary btn-mini' if current_user.system_admin? %>
  </h1>
</div>

<%= form_tag downloaders_path, method: :get, remote: true, id: "downloaders_search", class: 'form-search', data: { object: 'form-load' } do %>
  <%= hidden_field_tag :order %>
  <%= text_field_tag 'search', params[:search], class: 'search-query' %>
  <%= submit_tag 'Search', class: 'btn btn-primary' %>
<% end %>

<div id="downloaders"><center><%= image_tag "contour/ajax-loader.gif" %></center></div>

app/views/downloaders/index.js.erb
$("#downloaders").html("<%= escape_javascript(render("downloaders")) %>");

app/views/downloaders/new.html.erb
<% @title = "New Downloader" %>

<%= render 'form' %>

app/views/downloaders/show.html.erb
<% @title = "Downloader: #{@downloader.name}" %>
<div class="page-header">
  <h1>
    <%= @title %>
    <% if current_user.all_downloaders.include?(@downloader) %>
      <%= link_to 'Edit Downloader', edit_downloader_path(@downloader), class: 'btn btn-mini' %>
      <%= link_to 'Delete Downloader', @downloader, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: "Are you sure you want to delete Downloader #{@downloader.name}?" } %>
    <% end %>
    <%= link_to 'View Downloaders', downloaders_path, class: 'btn btn-mini' %>
  </h1>
</div>

<dl class="dl-horizontal">
  <dt>Creator</dt>
  <dd><%= link_to @downloader.user.name, @downloader.user %></dd>

  <dt>Files Digest</dt>
  <dd><tt><%= @downloader.files_digest %></tt></dd>

  <dt>Simple Executable file</dt>
  <dd><%= link_to File.basename(@downloader.simple_executable_file.path), SITE_URL + @downloader.simple_executable_file.url, :class => 'noicon' if @downloader.simple_executable_file and @downloader.simple_executable_file.url %></dd>

  <dt>Download token</dt>
  <dd><%= @downloader.download_token %></dd>

  <dt>External User ID</dt>
  <dd><%= @downloader.external_user_id %></dd>

  <dt>Download Count</dt>
  <dd><%= @downloader.downloader_segments.pluck(:download_count).sum %></dd>

  <dt>Checksum Count</dt>
  <dd><%= @downloader.downloader_segments.pluck(:checksum_count).sum %></dd>

  <dt>Downloader Segments [<%= @downloader.downloader_segments.size %>]</dt>
  <dd>
    <ul>
    <% @downloader.downloader_segments.order('download_count DESC').each do |downloader_segment| %>
      <li>D#: <%= downloader_segment.download_count %> C# <%= downloader_segment.checksum_count %> <%= link_to downloader_segment.segment.file_path.gsub(File.join(Rails.root, 'tmp', 'symbolic', @downloader.folder) + '/', ''), downloader_segment.segment if downloader_segment.segment %></li>
    <% end %>
    </ul>
  </dd>

  <dt>Comments</dt>
  <dd><%= @downloader.comments %></dd>
</dl>