config/routes.rb
Elastic::Application.routes.draw do

  resources :downloaders do
    member do
      get :download_file
    end
  end

  resources :segments

  devise_for :users, controllers: { registrations: 'contour/registrations', sessions: 'contour/sessions', passwords: 'contour/passwords', confirmations: 'contour/confirmations', unlocks: 'contour/unlocks' }, path_names: { sign_up: 'register', sign_in: 'login' }

  resources :users do
    member do
      post :update_settings
    end
  end

  get "/about" => "application#about", as: :about
  get "/settings" => "users#settings", as: :settings

  root to: "downloaders#index"

  # See how all your routes lay out with "rake routes"
end

app/models/segment.rb
class Segment < ActiveRecord::Base
  # attr_accessible :name, :checksum, :file_path

  # Concerns
  include Searchable

  # Named Scopes
  scope :current, -> { all }

  # Model Validation
  validates_presence_of :file_path
  validates_uniqueness_of :file_path

  # Model Relationships
  belongs_to :user
  has_many :downloader_segments
  has_many :downloaders, -> { where deleted: false }, through: :downloader_segments

  # Model Methods

  def generate_checksum!
    begin
      f = File.new(self.file_path)
      md5_checksum = Digest::MD5.hexdigest(f.read)
      self.update_attributes checksum: md5_checksum
    rescue StandardError, NoMemoryError => e
      logger.debug "Error #{e.inspect}"
      logger.debug "\nFile Size: #{(f || '').size}"
    ensure
      f.close if f and not f.closed?
      f = nil
    end
    self.checksum
  end

end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_system_admin
  before_action :set_segment, only: [ :show, :edit, :update, :destroy ]
  before_action :redirect_without_segment, only: [ :show, :edit, :update, :destroy ]

  # GET /segments
  # GET /segments.json
  def index
    @order = scrub_order(Segment, params[:order], 'segments.name')
    @segments = current_user.all_segments.search(params[:search]).order(@order).page(params[:page]).per(20)
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
  end

  # GET /segments/new
  def new
    @segment = current_user.segments.new
  end

  # GET /segments/1/edit
  def edit
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = current_user.segments.new(segment_params)

    respond_to do |format|
      if @segment.save
        format.html { redirect_to @segment, notice: 'Segment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @segment }
      else
        format.html { render action: 'new' }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /segments/1
  # PUT /segments/1.json
  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to @segment, notice: 'Segment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment.destroy

    respond_to do |format|
      format.html { redirect_to segments_path }
      format.json { head :no_content }
    end
  end

  private

    def set_segment
      @segment = current_user.all_segments.find_by_id(params[:id])
    end

    def redirect_without_segment
      empty_response_or_root_path unless @segment
    end

    def segment_params
      params.require(:segment).permit(
        :name, :checksum, :file_path
      )
    end

end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_form.html.erb
<div class="page-header">
  <h1><%= @title %></h1>
</div>

<%= form_for(@segment, html: { class: 'form-horizontal' }) do |f| %>
  <% if @segment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
      <% @segment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :user_id, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.number_field :user_id %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :name, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :file_path, nil, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :file_path, rows: 7, style: 'width:95%' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= cancel %>
  </div>
<% end %>

app/views/segments/_segments.html.erb
<%= render partial: 'contour/layouts/per_page', locals: { type: 'segments', object_count: @segments.total_count } %>

<table class="table table-striped table-bordered" style="width:100%">
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>File Path</th>
      <th>Download Count</th>
      <th>Checksum Count</th>
      <th>Actions</th>
    </tr>
  </thead>

  <% @segments.each do |segment| %>
    <tr>
      <td><%= segment.user_id %></td>
      <td><%= link_to segment.name, segment %></td>
      <td><%= link_to segment.file_path, segment %></td>
      <td><%= segment.downloader_segments.pluck(:download_count).sum %></td>
      <td><%= segment.downloader_segments.pluck(:checksum_count).sum %></td>
      <td>
        <%= link_to 'Edit', edit_segment_path(segment), class: 'btn btn-mini' %>
        <%= link_to 'Destroy', segment, :method => :delete, class: 'btn btn-mini btn-danger', data: { confirm: "Are you sure you want to delete Segment #{segment.name}?" } %>
    </tr>
  <% end %>
</table>


<center><%= paginate @segments, theme: "contour" %></center>

app/views/segments/edit.html.erb
<% @title = "Edit Segment: #{@segment.name}" %>

<%= render 'form' %>

app/views/segments/index.html.erb
<% @title = 'Segments' %>
<div class="page-header">
  <h1>
    <%= @title %>
    <%= link_to "Create Segment", new_segment_path, class: 'btn btn-primary btn-mini' if current_user.system_admin? %>
  </h1>
</div>

<%= form_tag segments_path, method: :get, remote: true, id: "segments_search", class: 'form-search', data: { object: 'form-load' } do %>
  <%= hidden_field_tag :order %>
  <%= text_field_tag 'search', params[:search], class: 'search-query' %>
  <%= submit_tag 'Search', class: 'btn btn-primary' %>
<% end %>

<div id="segments"><center><%= image_tag "contour/ajax-loader.gif" %></center></div>

app/views/segments/index.js.erb
$("#segments").html("<%= escape_javascript(render("segments")) %>");

app/views/segments/new.html.erb
<% @title = "New Segment" %>

<%= render 'form' %>

app/views/segments/show.html.erb
<% @title = "Segment: #{@segment.name}" %>
<div class="page-header">
  <h1>
    <%= @title %>
    <% if current_user.all_segments.include?(@segment) %>
      <%= link_to 'Edit Segment', edit_segment_path(@segment), class: 'btn btn-mini' %>
      <%= link_to 'Delete Segment', @segment, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: "Are you sure you want to delete Segment #{@segment.name}?" } %>
    <% end %>
    <%= link_to 'View Segments', segments_path, class: 'btn btn-mini' %>
  </h1>
</div>

<dl class="dl-horizontal">
  <dt>User</dt>
  <dd><%= @segment.user_id %></dd>

  <dt>File Path</dt>
  <dd><%= @segment.file_path %></dd>

  <dt>Download Count</dt>
  <dd><%= @segment.downloader_segments.pluck(:download_count).sum %></dd>

  <dt>Checksum Count</dt>
  <dd><%= @segment.downloader_segments.pluck(:checksum_count).sum %></dd>

  <dt>Downloaders [<%= @segment.downloaders.size %>]</dt>
  <dd>
    <ul>
    <% @segment.downloaders.each do |downloader| %>
      <%= link_to downloader.name, downloader %>
    <% end %>
    </ul>
  </dd>
</dl>